### ISSUE TITLE
Pug - enable pretty

### ISSUE THREAD

**Issue by maxlanser** [DougBeney/Jekyll-Bliss#1]
How to add the Pug option `pretty: true` ?
Many Thanks!)

**Comment by DougBeney** [comment]
Hi, Max! That's something I need to add but it should be super easy. I can probably have it done by the end of today.

**Comment by DougBeney** [comment]
Support added in newest version :)

Run `npm update -g jekyll-bliss` to get it.

Now, you can pass any options [from Pug's API](https://pugjs.org/api/reference.html) including `pretty`.

Example `_config.yml`:

```yaml
pug:
  pretty: true
```
