### ISSUE TITLE
Which is the canonical repo? The one on GitHub or GitLab?

### ISSUE THREAD

**Issue by ErikBjare** [DougBeney/Jekyll-Bliss#3]
The GitHub repo is the top result on Google, but the website links to GitLab. So, which is it?

**Comment by DougBeney** [comment]
Sorry about that. Haven't messed with the website for a while. I'm back on Github now. :)

**Comment by ErikBjare** [comment]
No worries, just wondering because I have some weird issue with pngs being mangled and didn't know where to report the issue.

We're using jekyll-bliss for https://activitywatch.net ([GitHub](https://github.com/ActivityWatch/activitywatch.github.io)) and it works a treat. Thanks for working on it!

**Comment by DougBeney** [comment]
No way! I've used that project plenty of times. Never knew the site used Bliss :)
